language: node_js

node_js:
  - lts/*

notifications:
  email:
    if: branch = master
    on_success: never
    on_failure: always

cache:
  yarn: true

install:
  - yarn --frozen-lockfile
  - yarn global add codecov

script:
  - yarn test:ci
  - codecov
  - yarn package
